//
//  Event+Extensions.h
//  BolusCalc
//
//  Created by Uwe Petersen on 01.07.13.
//  Copyright (c) 2013 Uwe Petersen. All rights reserved.
//
//  Extensions to the class Event which was autogenerated by core data
//  Needed for instance to handle the date information used in section titles
//

#import "Event.h"

@interface Event (Extensions)


// Properties for calculation and population of the section titles
@property (nonatomic, retain) NSDate   *primitiveTimeStamp;
@property (nonatomic, retain) NSString *primitiveDayString;


// shortBolus
-(void) setShortBolusForCorrectionBolusForChuBolus;

// correctionBolus
-(void) setCorrectionDivisorForCorrectionBolusForBloodSugarForBloodSugarGoal;
-(void) setCorrectionBolusForCorrectionDivisorForBloodSugarForBloodSugarGoal;

// chuBolus
-(void) setChuForCarb;
-(void) setChuBolusForChuFactorForChu;
-(void) setChuFactorForChuBolusForChu;
-(void) setChuFactorToChuFactorDefaultValueIfNil;

// fpuBolus
-(void) setFpuForFatForProtein;
-(void) setFpuBolusForFpuFactorForFpu;
-(void) setFpuFactorForFpuBolusForFpu;
-(void) setFpuFactorToFpuFactorDefaultValueIfNil;


// Time and date stuff
-(NSNumber *) hourOfDay;

@end
